### ISSUE TITLE
Latest release was not pushed to docker hub

### ISSUE THREAD

**Issue by LucasAdam** [etlegacy/etlegacy#2263]
It looks like the 2.81.0 release didn't get pushed to [docker hub](https://hub.docker.com/r/etlegacy/server/tags?page=1) with the `latest` tag 

![image](https://user-images.githubusercontent.com/9447241/218128648-eccf3784-8b4d-4054-b14d-015fc0033d57.png)

Maybe it is due to this condition in the workflow ? 

`if: steps.vars.outputs.tag == steps.vars.outputs.short_tag && steps.vars.outputs.tag_exists == '404' && github.event_name != 'schedule'`

**Comment by rafal1137** [comment]
Here is a part of those Builds for docker
```yml
      # Create weekly tag when scheduled and update when triggered on docker hub
      - name: Build and push the weekly Docker image
        if: ${{ github.event_name == 'schedule' }}
        working-directory: build/package
        run: |
          docker build . --file Dockerfile --tag etlegacy/server:weekly
          docker push etlegacy/server:weekly
      # If we are on a release tag, then also create the 'latest' tag on docker hub
      - name: Build and push the latest Docker image
        if: steps.vars.outputs.tag == steps.vars.outputs.short_tag && steps.vars.outputs.tag_exists == '404' && github.event_name != 'schedule'
        working-directory: build/package
        run: |
          docker build . --file Dockerfile --tag etlegacy/server:latest --tag etlegacy/server:${{ steps.vars.outputs.tag }}
          docker push etlegacy/server:${{steps.vars.outputs.tag}}
          docker push etlegacy/server:latest
      # If we are on any build, then also create the 'latest-patch' tag on docker hub
      - name: Build and push the latest patch Docker image
        if: github.event_name != 'schedule'
        working-directory: build/package
        run: |
          docker build . --file Dockerfile --tag etlegacy/server:latest-patch
          docker push etlegacy/server:latest-patch
```

All of those 3 corresponding for all those 3 jobs they are executed when specific value/time are met.
The one with tagging should be executed when there is new tag and not already in existence and with not scheduled one `weekly builds`
